import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import classNames from 'classnames/bind';
import { Provider as JotaiProvider } from 'jotai';

import Header from '@/layouts/Header';
import Footer from '@/layouts/Footer';
import Initializer from '@/components/Initializer/Initializer.server';
import { Darkmode, DARKMODE_COOKIE } from '@/constants/cookie.constant';
import { ApolloNextProvider } from '@/libs/apollo/apollo.client';

import styles from './layout.module.scss';

import '@/styles/normalize.scss';
import '@/styles/global.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const cx = classNames.bind(styles);

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const darkmode = (cookieStore.get(DARKMODE_COOKIE)?.value || Darkmode.LIGHT) as Darkmode;

  return (
    <html lang="ko" data-theme={darkmode}>
      <body>
        <ApolloNextProvider cookie={cookieStore.toString()}>
          <JotaiProvider>
            <Initializer>
              <div id="next-section" className={cx('next-root')}>
                <Header darkmodeCookie={darkmode} />
                <main className={cx('next-content')}>{children}</main>
                <Footer />
              </div>
            </Initializer>
          </JotaiProvider>
        </ApolloNextProvider>
        <div id="next-portal"></div>
      </body>
    </html>
  );
}
