name: chanyeong-client-build

on:
  push:
    branches:
      - master
      - develop

env:
  DOCKER_CONTAINER: chanyeong-client

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.DOCKER_REGISTRY_URL}}
          username: ${{secrets.DOCKER_REGISTRY_ACCESS_KEY}}
          password: ${{secrets.DOCKER_REGISTRY_SECRET_KEY}}

      - name: Docker build & push to push
        run: docker buildx build --platform linux/arm64/v8 -t ${{secrets.DOCKER_REGISTRY_URL}}/${{secrets.DOCKER_REPO}}:${{ github.sha }} -t ${{secrets.DOCKER_REGISTRY_URL}}/${{secrets.DOCKER_REPO}}:latest --push .
